import streamlit as st
import pandas as pd
import joblib


st.set_page_config(
    page_title="Loan Approval Predictor",
    page_icon="🏦",
    layout="centered"
)

model = joblib.load("loan_approval_model.pkl")
scaler = joblib.load("loan_scaler.pkl")
expected_columns = joblib.load("loan_columns.pkl")

st.title("🏦 Loan Approval Predictor")
st.markdown(
    "Enter the applicant's financial and loan details below "
    "to predict the loan approval status."
)

st.subheader("👤 Applicant Information")

st.markdown("### Personal & Employment")
person_age  = st.number_input(
    "Age",
    min_value=20,
    max_value=80,
    value=25
)

person_income = st.number_input(
    "Annual Income",
    min_value=4200,
    value=50000
)

person_home_ownership = st.selectbox(
    "Home Ownership",
    ["RENT","MORTGAGE","OWN","OTHER"]
)
loan_intent = st.selectbox(
    "Loan Intent",
    [
        "EDUCATION",
        "MEDICAL",
        "PERSONAL",
        "VENTURE",
        "DEBTCONSOLIDATION",
        "HOMEIMPROVEMENT"
    ]
)

loan_grade = st.selectbox(
    "Loan Grade",
    ["A","B","C","D","E","F","G"]
)

cb_person_default_on_file = st.selectbox(
    "Previous Default on file",
    ["N","Y"]
)

person_emp_length = st.number_input(
    "Employment length(years)",
    min_value = 0,
    max_value=40,
    value=4
)

st.markdown("### 💰 Loan Information")
loan_amnt = st.number_input(
    "Loan Amount",
    min_value = 500,
    max_value= 35000,
    value=8000
)

loan_int_rate = st.number_input(
    "Loan Interest Rate(%)",
    min_value=5.42,
    max_value=23.22,
    value=10.75
)

loan_percent_income = st.number_input(
    "Loan percent of income",
    min_value=0.0,
    max_value=0.83,
    value=0.14
)

st.markdown("### 🏦 Credit Information")
cb_person_cred_hist_length = st.number_input(
    "Credit History Length(years)",
    min_value=2,
    max_value=30,
    value=4
    
)

input_data = pd.DataFrame({
    "person_age": [person_age],
    "person_income": [person_income],
    "person_home_ownership": [person_home_ownership],
    "person_emp_length": [person_emp_length],
    "loan_intent": [loan_intent],
    "loan_grade": [loan_grade],
    "loan_amnt": [loan_amnt],
    "loan_int_rate": [loan_int_rate],
    "loan_percent_income": [loan_percent_income],
    "cb_person_default_on_file": [cb_person_default_on_file],
    "cb_person_cred_hist_length": [cb_person_cred_hist_length]
})

input_data = pd.get_dummies(
    input_data,
    columns=[
         "person_home_ownership",
        "loan_intent",
        "loan_grade",
        "cb_person_default_on_file"
    ],
    drop_first=True
)

input_data = input_data.reindex(
    columns=expected_columns,
    fill_value=0
)


numeric_cols = [
    "person_age",
    "person_income",
    "person_emp_length",
    "loan_amnt",
    "loan_int_rate",
    "loan_percent_income",
    "cb_person_cred_hist_length"
]

input_data[numeric_cols] = scaler.transform(
    input_data[numeric_cols]
)




st.markdown("---")

st.subheader("🔮 Prediction")

if st.button("🚀 Predict Loan Status", use_container_width=True):

    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.success("✅ Loan Approved")
        st.write("The model predicts that this loan application is likely to be approved.")
    else:
        st.error("❌ Loan Not Approved")
        st.write("The model predicts that this loan application is likely to be rejected.")
        
        
st.markdown("---")

st.caption(
    "⚠️ This application is for educational purposes only. "
    "Predictions are generated by a machine learning model and "
    "should not be considered a real financial decision."
)